const icons  = {
  sun: require('./sun.png'),
  moon: require('./moon.png'),
  add: require('./add.png'),
  archive: require('./archive.png'),
  back: require('./back.png'),
  forward: require("./forward.png"),
  menu: require('./menu.png'),
  newChat: require('./newChat.png'),
  search: require('./search.png'),
  contactActive: require("./contactActive.png"),
  contactInactive: require("./contactInactive.png"),
  chatActive: require("./chatActive.png"),
  chatInactive: require("./chatInactive.png"),
  moreActive: require("./moreActive.png"),
  moreInactive: require("./moreInactive.png"),
  dotActive: require("./dotActive.png"),
  addStory: require("./addStory.png"),
  defaultAccountImageLight: require("./defaultAccountImageLight.png"),
  addImageLight: require("./addImageLight.png"),
  defaultAccountImageDark: require("./defaultAccountImageDark.png"),
  addImageDark: require("./addImageDark.png"),
  account: require("./account.png"),
  appereance: require("./appereance.png"),
  notifications: require("./notifications.png"),
  privacy: require("./privacy.png"),
  dataUsage: require("./dataUsage.png"),
  help: require("./help.png"),
  invite: require("./invite.png"),
}; 

export default icons;